In [6]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import numpy as np

In [18]:
df = pd.read_csv('/content/drive/MyDrive/Machine_Learning_Google_Colab/student_scores.csv')
df

,Unnamed: 0,Gender,EthnicGroup,ParentEduc,LunchType,TestPrep,MathScore,ReadingScore,WritingScore
0,0,female,group B,bachelor's degree,standard,none,72,72,74
1,1,female,group C,some college,standard,completed,69,90,88
2,2,female,group B,master's degree,standard,none,90,95,93
3,3,male,group A,associate's degree,free/reduced,none,47,57,44
4,4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...,...
30636,995,male,group C,some high school,standard,none,56,47,51
30637,996,male,group E,associate's degree,free/reduced,none,74,75,72
30638,997,male,group C,some college,standard,none,36,29,27
30639,998,male,group A,some high school,free/reduced,completed,43,34,39
30640,999,female,group D,associate's degree,standard,none,52,68,66

In [9]:
[x.lower() for x in df.columns]

['unnamed: 0',
 'gender',
 'ethnicgroup',
 'parenteduc',
 'lunchtype',
 'testprep',
 'mathscore',
 'readingscore',
 'writingscore']

In [10]:
df.drop_duplicates()

,Unnamed: 0,Gender,EthnicGroup,ParentEduc,LunchType,TestPrep,MathScore,ReadingScore,WritingScore
0,0,female,group B,bachelor's degree,standard,none,72,72,74
1,1,female,group C,some college,standard,completed,69,90,88
2,2,female,group B,master's degree,standard,none,90,95,93
3,3,male,group A,associate's degree,free/reduced,none,47,57,44
4,4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...,...
30636,995,male,group C,some high school,standard,none,56,47,51
30637,996,male,group E,associate's degree,free/reduced,none,74,75,72
30638,997,male,group C,some college,standard,none,36,29,27
30639,998,male,group A,some high school,free/reduced,completed,43,34,39
30640,999,female,group D,associate's degree,standard,none,52,68,66

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30641 entries, 0 to 30640
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    30641 non-null  int64
 1   Gender        30641 non-null  object
 2   EthnicGroup   30641 non-null  object
 3   ParentEduc    30641 non-null  object
 4   LunchType     30641 non-null  object
 5   TestPrep      30641 non-null  object
 6   MathScore     30641 non-null  int64
 7   ReadingScore  30641 non-null  int64
 8   WritingScore  30641 non-null  int64
dtypes: int64(4), object(5)
memory usage: 2.1+ MB

In [13]:
df.describe()

         Unnamed: 0     MathScore  ReadingScore  WritingScore
count  30641.000000  30641.000000  30641.000000  30641.000000
mean     499.556607     66.749355     69.624980     68.468327
std      288.747894     15.206049     14.671572     15.307814
min        0.000000      0.000000     10.000000      5.000000
25%      249.000000     56.000000     60.000000     58.000000
50%      500.000000     67.000000     70.000000     69.000000
75%      750.000000     78.000000     80.000000     79.000000
max      999.000000    100.000000    100.000000    100.000000

In [15]:
df[0:]

,Unnamed: 0,Gender,EthnicGroup,ParentEduc,LunchType,TestPrep,MathScore,ReadingScore,WritingScore
0,0,female,group B,bachelor's degree,standard,none,72,72,74
1,1,female,group C,some college,standard,completed,69,90,88
2,2,female,group B,master's degree,standard,none,90,95,93
3,3,male,group A,associate's degree,free/reduced,none,47,57,44
4,4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...,...
30636,995,male,group C,some high school,standard,none,56,47,51
30637,996,male,group E,associate's degree,free/reduced,none,74,75,72
30638,997,male,group C,some college,standard,none,36,29,27
30639,998,male,group A,some high school,free/reduced,completed,43,34,39
30640,999,female,group D,associate's degree,standard,none,52,68,66

In [19]:
df['TotalScore'] = df['MathScore'] + df['ReadingScore'] + df['WritingScore']
df

,Unnamed: 0,Gender,EthnicGroup,ParentEduc,LunchType,TestPrep,MathScore,ReadingScore,WritingScore,TotalScore
0,0,female,group B,bachelor's degree,standard,none,72,72,74,218
1,1,female,group C,some college,standard,completed,69,90,88,247
2,2,female,group B,master's degree,standard,none,90,95,93,278
3,3,male,group A,associate's degree,free/reduced,none,47,57,44,148
4,4,male,group C,some college,standard,none,76,78,75,229
...,...,...,...,...,...,...,...,...,...,...
30636,995,male,group C,some high school,standard,none,56,47,51,154
30637,996,male,group E,associate's degree,free/reduced,none,74,75,72,221
30638,997,male,group C,some college,standard,none,36,29,27,92
30639,998,male,group A,some high school,free/reduced,completed,43,34,39,116
30640,999,female,group D,associate's degree,standard,none,52,68,66,186

In [21]:
colab_exercise = df.to_csv('/content/drive/MyDrive/Machine_Learning_Google_Colab/colab_exercise.csv')

In [24]:
type(colab_exercise)

NoneType